image: registry.gitlab.com/pushmestudio/kcuc-ee

variables:
  TARGET_IP: ""
  TARGET_DIR: ""
  KEY_FILE: ""
  WAR_PROJECT: ""
  WAR_NAME: ""

before_script:
- chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew -g /cache/.gradle clean build
  allow_failure: false

deploy:
  stage: deploy
  only:
  - production
  script:
  - ./gradlew -g /cache/.gradle war
  - scp -i ${KEY_FILE} ../${WAR_PROJECT}/build/libs/${WAR_NAME}.war ${TARGET_IP}:${TARGET_DIR}
