variables:
  TARGET_IP: ""
  TARGET_DIR: ""
  IMAGE_NAME: "registry.gitlab.com/pushmestudio/kcuc-ee"
  KEY_FILE: ""
  WAR_PROJECT: ""
  WAR_NAME: "kcuc.war"

# it needs to deploy phase
services:
  - docker:dind

before_script:
  - chmod +x ./gradlew

build_job:
  image: "${IMAGE_NAME}:devel"
  stage: build
  script:
    - ./gradlew -g /cache/.gradle clean assemble
  allow_failure: false
  # reserve war file for deploy
  artifacts:
    paths:
      - "build/libs/${WAR_NAME}"
    expire_in: 1 week

test_job:
  image: "${IMAGE_NAME}:devel"
  stage: test
  script:
    - ./gradlew -g /cache/.gradle check

deploy_job:
  image: docker:latest
  stage: deploy
  # prerequire the build/libs/kcuc.war
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t "${IMAGE_NAME}:latest" --build-arg CLOUDANT_ACCOUNT="${CLOUDANT_ACCOUNT}" --build-arg CLOUDANT_USER="${CLOUDANT_USER}" --build-arg CLOUDANT_PW="${CLOUDANT_PW}" .
    - docker push "${IMAGE_NAME}:latest"
  only:
    - master
